config/routes.rb
Rails.application.routes.draw do
  root to: 'statistics#index'

  get 'statistics/', to: 'statistics#index'

  resources :merge_requests do
    get 'by_month', on: :collection
    get 'mttp_with_development', on: :collection
    get 'mttp', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merge_request.rb
class MergeRequest < ApplicationRecord
  enum status: [:opened, :closed, :merged]

  scope :by_month, ->(start_month, end_month) { where(created_at_gitlab: start_month..end_month) }
  scope :merged, -> { where.not(merged_at: nil) }
  scope :by_created_at, -> { order(:created_at_gitlab) }
  scope :by_merged_at, -> { order(:merged_at) }
  scope :on_production, -> { where.not(production_at: nil) }

  def self.average_mttp(merge_requests)
    time = 0

    merge_requests.each do |merge_request|
      time += merge_request.time_between_merged_and_production
    end

    time.to_f / merge_requests.count.to_f
  end

  def self.average_mttp_with_development(merge_requests)
    time = 0

    merge_requests.each do |merge_request|
      time += merge_request.time_between_opened_and_production
    end

    time.to_f / merge_requests.count.to_f
  end

  def self.merged_csv
    attributes = %w{gitlab_path created_at_gitlab merged_at staging_at canary_at production_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      merged.by_merged_at.each do |merge_request|
        csv << attributes.map{ |attr| merge_request.send(attr) }
      end
    end
  end

  def self.mttp_with_development_csv
    attributes = %w{gitlab_path time_between_opened_and_production time_between_development_and_merged time_between_merged_and_staging time_between_staging_and_canary time_between_canary_and_production}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      merged.by_merged_at.each do |merge_request|
        csv << attributes.map{ |attr| merge_request.send(attr) }
      end
    end
  end

  def self.mttp_csv
    attributes = %w{gitlab_path time_between_merged_and_production time_between_merged_and_staging time_between_staging_and_canary time_between_canary_and_production}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      merged.by_merged_at.each do |merge_request|
        csv << attributes.map{ |attr| merge_request.send(attr) }
      end
    end
  end

  def gitlab_path
    "https://gitlab.com/gitlab-org/gitlab/merge_requests/#{gitlab_id}"
  end

  def time_between_development_and_merged
    (merged_at.to_date - created_at_gitlab.to_date).to_i
  end

  def time_between_merged_and_staging
    return 0 if staging_at.nil?

    (staging_at.to_date - merged_at.to_date).to_i
  end

  def time_between_staging_and_canary
    return 0 if staging_at.nil? || canary_at.nil?

    (canary_at.to_date - staging_at.to_date).to_i
  end

  def time_between_canary_and_production
    return 0 if canary_at.nil? || production_at.nil?

    (production_at.to_date - canary_at.to_date).to_i
  end

  def time_between_merged_and_production
    return 0 if production_at.nil?

    (production_at.to_date - merged_at.to_date).to_i
  end

  def time_between_opened_and_production
    return 0 if production_at.nil?

    (production_at.to_date - created_at_gitlab.to_date).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/merge_requests_controller.rb
class MergeRequestsController < ApplicationController
  before_action :set_date

  def by_month
    @merge_requests = MergeRequest
      .by_month(@date.beginning_of_month, @date.end_of_month)

    respond_to do |format|
      format.html
      format.csv do
        send_data MergeRequest.merged_csv, filename: "merge_requests-merged-#{@date.to_s}.csv" 
      end
    end
  end

  def mttp_with_development
    @merge_requests = MergeRequest
      .merged
      .by_month(@date.beginning_of_month, @date.end_of_month)

    respond_to do |format|
      format.html
      format.csv do
        send_data MergeRequest.mttp_with_development_csv, filename: "mtt-with-development-#{@date.to_s}.csv" 
      end
    end
  end

  def mttp
    @merge_requests = MergeRequest
      .merged
      .by_month(@date.beginning_of_month, @date.end_of_month)

    respond_to do |format|
      format.html
      format.csv do
        send_data MergeRequest.mttp_csv, filename: "mttp-#{@date.to_s}.csv" 
      end
    end
  end

  private

  def set_date
    @date = params[:date].to_date
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @september = "01-09-2019".to_date
    @september_mrs_total = MergeRequest
      .by_month(@september.beginning_of_month, @september.end_of_month)
      .count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/merge_requests_helper.rb
module MergeRequestsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeantimeToProduction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/merge_requests/by_month.html.erb
<h2><%= "Merge Requests on #{@date.strftime("%B/%y")}" %></h2>

<%= link_to "CSV", by_month_merge_requests_path(date: @date, format: 'csv') %>

<h3>Summary</h3>

<table>
  <tbody>
    <tr>
      <td>Total</td><td><%= @merge_requests.count %></td>
    </tr>
    <tr>
      <td>Opened</td><td><%= @merge_requests.opened.count %></td>
    </tr>
    <tr>
      <td>Merged</td><td><%= @merge_requests.merged.count %></td>
    </tr>
    <tr>
      <td>Closed</td><td><%= @merge_requests.closed.count %></td>
    </tr>
    <tr>
      <td>Deploy to Production</td>
      <td><%= @merge_requests.on_production.count %></td>
    </tr>
  </tbody>
</table>

<hr>

<h3>Details</h3>

<table>
  <thead>
    <th>Merge Request ID</th>
    <th>Created at</th>
    <th>Merged at</th>
    <th>Staging at</th>
    <th>Canary at</th>
    <th>Production at</th>
  </thead>
  <tbody>
    <% @merge_requests.merged.by_merged_at.each do |merge_request| %>
      <tr>
        <td><%= link_to merge_request.gitlab_path, merge_request.gitlab_path, target: 'blank' %></td>
        <td><%= merge_request.created_at_gitlab.strftime("%F %H:%M") %></td>
        <td><%= merge_request.merged_at.strftime("%F %H:%M") %></td>
        <td><%= merge_request.staging_at&.strftime("%F %H:%M") %></td>
        <td><%= merge_request.canary_at&.strftime("%F %H:%M") %></td>
        <td><%= merge_request.production_at&.strftime("%F %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/merge_requests/mttp.html.erb
<h3>Measure Mean Time To Production</h3>

<%= link_to "CSV", mttp_merge_requests_path(date: @date, format: 'csv') %>

<table>
  <thead>
    <tr>
      <td>Total: </td>
      <td><%= @merge_requests.count %></td>
    </tr>

    <tr>
      <td>Average time between Merged and Production</td>
      <td><%= MergeRequest.average_mttp(@merge_requests) %></td>
    </tr>
  </thead>
</table>

<table>
  <thead>
    <th>Merge Request ID</th>
    <th>Total Time (Time between Merged and Production)</th>
    <th>Time between Merged and Staging</th>
    <th>Time between Staging and Canary</th>
    <th>Time between Canary and Production</th>
  </thead>
  <tbody>
    <% @merge_requests.by_created_at.each do |merge_request| %>
      <tr>
        <td><%= link_to merge_request.gitlab_path, merge_request.gitlab_path, target: 'blank' %></td>
        <td><%= merge_request.time_between_merged_and_production %></td>
        <td><%= merge_request.time_between_merged_and_staging %></td>
        <td><%= merge_request.time_between_staging_and_canary %></td>
        <td><%= merge_request.time_between_canary_and_production %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/merge_requests/mttp_with_development.html.erb
<h3>Measure Mean Time To Production (with Development)</h3>

<%= link_to "CSV", mttp_with_development_merge_requests_path(date: @date, format: 'csv') %>

<table>
  <thead>
    <tr>
      <td>Total: </td>
      <td><%= @merge_requests.count %></td>
    </tr>
    <tr>
      <td>Average time between Opened and Production</td>
      <td><%= MergeRequest.average_mttp_with_development(@merge_requests) %></td>
    </tr>
  </thead>
</table>

<table>
  <thead>
    <th>Merge Request ID</th>
    <th>Time between Opened and Production</th>
    <th>Time between Opened and Merged</th>
    <th>Time between Merged and Staging</th>
    <th>Time between Staging and Canary</th>
    <th>Time between Canary and Production</th>
  </thead>
  <tbody>
    <% @merge_requests.by_created_at.each do |merge_request| %>
      <tr>
        <td><%= link_to merge_request.gitlab_path, merge_request.gitlab_path, target: 'blank' %></td>
        <td><%= merge_request.time_between_opened_and_production %></td>
        <td><%= merge_request.time_between_development_and_merged %></td>
        <td><%= merge_request.time_between_merged_and_staging %></td>
        <td><%= merge_request.time_between_staging_and_canary %></td>
        <td><%= merge_request.time_between_canary_and_production %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/statistics/index.html.erb
<h3>Statistics by month</h3>

<table>
  <thead>
    <th>Month</th>
    <th>Merge Requests</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @september.strftime("%B") %></td>
      <td><%= link_to "Merge Requests", by_month_merge_requests_path(date: @september.to_s) %></td>
      <td><%= link_to "MTTP with development", mttp_with_development_merge_requests_path(date: @september.to_s) %></td>
      <td><%= link_to "MTTP", mttp_merge_requests_path(date: @september.to_s) %></td>
    </tr>
  </tbody>
</table>